apiVersion: v1
kind: ConfigMap
metadata:
  name: model-serving-config
data:
  config.yaml: |
    modelMeshImage:
      name: image-registry.openshift-image-registry.svc:5000/__NAMESPACE__/model-mesh
      tag: latest
