apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: dte-nfs-storage
 labels:
   billingType: hourly
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 
 storageClassName: ibmc-file-gold